CMDataset.GEOJSON=1;CMDataset.PYRAMID=2;CMDataset.PYRAMID_OPEN_FORMAT=3;CMDataset.RASTER=4;CMDataset.SQL=5;CMDataset.MESSAGE_DATASET_LOADED=CMBase.GetUniqueNumber();CMDataset.MESSAGE_DATASET_SELECTION_CHANGED=CMBase.GetUniqueNumber();CMDataset.MESSAGE_DATASET_MOUSE_OVER_FEATURE_CHANGED=CMBase.GetUniqueNumber();CMDataset.LOAD_STATUS_NONE=1;CMDataset.LOAD_STATUS_LOADING=2;CMDataset.LOAD_STATUS_LOADED=3;CMDataset.LOAD_STATUS_PENDING=4;CMDataset.LOAD_STATUS_CANCELED=5;CMDataset.REQUEST_TYPE_IMAGE=1;CMDataset.REQUEST_TYPE_TEXT=2;CMDataset.RequestQue=[];CMDataset.CurrentRequest=null;CMDataset.MakeRequest=function(TheRequest){TheRequest.TheImage.TheRequest=TheRequest;TheRequest.TheImage.onload=function(){this.TheRequest.LoadStatus=CMDataset.LOAD_STATUS_LOADED;if(CMDataset.RequestQue.length>0){CMDataset.CurrentRequest=CMDataset.RequestQue[0];CMDataset.RequestQue.shift();CMDataset.CurrentRequest.LoadStatus=CMDataset.LOAD_STATUS_LOADING;CMDataset.CurrentRequest.TheImage.src=CMDataset.CurrentRequest.src;}else{CMDataset.CurrentRequest=null;}this.TheRequest.TheFunction();}
if(CMDataset.CurrentRequest==null){CMDataset.CurrentRequest=TheRequest;TheRequest.LoadStatus=CMDataset.LOAD_STATUS_LOADING;TheRequest.TheImage.src=TheRequest.src;}else{TheRequest.LoadStatus=CMDataset.LOAD_STATUS_PENDING;CMDataset.RequestQue.push(TheRequest);}}
CMDataset.ResetRequests=function(){var CurrentRequests=CMDataset.RequestQue;CMDataset.RequestQue=[];for(var i=0;i<CurrentRequests.length;i++){var TheRequest=CurrentRequests[i];CurrentRequests[i]=null;TheRequest.LoadStatus=CMDataset.LOAD_STATUS_CANCELED;}}
function CMDataset(){CMBase.call(this);this.URL=null;this.SelectedFeature=-1;this.MouseOverFeatureIndex=-1;this.ClickTolerance=8;}CMDataset.prototype=Object.create(CMBase.prototype);CMDataset.prototype.contructor=CMDataset;CMDataset.prototype.GetNumAttributeRows=function(){return(0);}
CMDataset.prototype.GetNumAttributeColumns=function(){return(0);}
CMDataset.prototype.GetAttributeHeading=function(ColumnIndex){return("");}
CMDataset.prototype.GetAttributeCell=function(ColumnIndex,RowIndex){return("");}
CMDataset.prototype.AddAttributeHeading=function(NewHeading,DefaultValue){}
CMDataset.prototype.GetAttributeCellByHeading=function(Heading,RowIndex){return("");}
CMDataset.prototype.SetAttributeCell=function(ColumnIndex,RowIndex,Value){"use strict";};CMDataset.prototype.SetAttributeCellByHeading=function(Heading,RowIndex,Value){};CMDataset.prototype.GetAttributeArrayByHeading=function(Heading){var NumAttributeRows=this.GetNumAttributeRows();var Result=[];for(var i=0;i<NumAttributeRows;i++){Result[i]=this.GetAttributeCellByHeading(Heading,i);}return(Result);}
CMDataset.prototype.SetProjector=function(NewProjector){this.TheProjector=NewProjector;}
CMDataset.prototype.GetProjector=function(){return(this.TheProjector);}
CMDataset.prototype.SetURL=function(URL,ZoomToBounds){alert("TCMDataset.SetURL() should be overriden in a subclass");};CMDataset.prototype.SetData=function(TheData){this.TheData=TheData;};CMDataset.prototype.GetNumFeatures=function(){return(0);}
CMDataset.prototype.InFeature=function(TheView,RefX,RefY,FeatureIndex){return(false);}
CMDataset.prototype.In=function(TheView,RefX,RefY){var FeatureIndex=-1;return(FeatureIndex);};CMDataset.prototype.Paint=function(TheLayer,TheView,SelectedOnly){};CMDataset.prototype.GetSearchResults=function(SearchPhrase,ResultsPanel){}
CMDataset.prototype.GetIcon=function(TheLayer,Default){return(Default);}
CMDataset.prototype.SetSelectedFeature=function(NewSelectedFeatureIndex){if(this.SelectedFeature!=NewSelectedFeatureIndex){this.SelectedFeature=NewSelectedFeatureIndex;this.SendMessageToListeners(CMDataset.MESSAGE_DATASET_SELECTION_CHANGED);}}
CMDataset.prototype.GetSelectedFeature=function(){return(this.SelectedFeature);}
CMDataset.prototype.SetMouseOverFeature=function(NewMouseOverFeatureIndex){if(this.MouseOverFeatureIndex!=NewMouseOverFeatureIndex){this.MouseOverFeatureIndex=NewMouseOverFeatureIndex;this.SendMessageToListeners(CMDataset.MESSAGE_DATASET_MOUSE_OVER_FEATURE_CHANGED);}}
CMDataset.prototype.GetMouseOverFeature=function(){return(this.MouseOverFeatureIndex);}
CMDataset.prototype.AddPoint=function(X,Y){}
CMDataset.TheDataSets=[];CMDataset.GetDataObject=function(URL,DataSetType){var TheDataSet=null;for(var i=0;i<CMDataset.TheDataSets.length;i++){if(CMDataset.TheDataSets[i].URL==URL)TheDataSet=CMDataset.TheDataSets[i];}if(TheDataSet==null){switch(DataSetType){case CMDataset.GEOJSON:case undefined:TheDataSet=new CMDatasetGeoJSON();break;case CMDataset.PYRAMID:TheDataSet=new CMDatasetPyramid();break;case CMDataset.PYRAMID_OPEN_FORMAT:TheDataSet=new CMDatasetPyramidOpenFormat();break;case CMDataset.RASTER:alert("Sorry, CMDataset.RASTER is not yet supported");break;case CMDataset.SQL:TheDataSet=new CMDatasetSQL();break;}CMDataset.TheDataSets.push(TheDataSet);}return(TheDataSet);}