CMDialog.DIALOG_WIDTH=400;CMDialog.DIALOG_HEIGHT=400;CMDialog.CreateCloseBox=function(TheDialog,X,Y,CloseBoxWidth,CloseBoxHeight,TheColor){var CloseBox=document.createElement("canvas");CMUtilities.AbsolutePosition(CloseBox,X,Y,CloseBoxWidth,CloseBoxHeight);CloseBox.style.border="1px solid "+TheColor;CloseBox.width=CloseBoxWidth;CloseBox.height=CloseBoxHeight;if(TheDialog instanceof CMDialog)TheDialog.TheElement.appendChild(CloseBox);else TheDialog.appendChild(CloseBox);CloseBox.TheDialog=TheDialog;CloseBox.onmousedown=function(TheEvent){if(this.TheDialog instanceof CMDialog)this.TheDialog.SetVisible(false);else this.TheDialog.style.visibility="hidden";};CMDialog.PaintCloseBox(CloseBox,CloseBoxWidth,CloseBoxHeight,TheColor);return(CloseBox);}
CMDialog.PaintCloseBox=function(CloseBox,CloseBoxWidth,CloseBoxHeight,TheColor){var TheContext=CloseBox.getContext("2d");TheContext.strokeStyle=TheColor;TheContext.lineWidth=2;TheContext.beginPath();TheContext.moveTo(0,0);TheContext.lineTo(CloseBoxWidth,CloseBoxHeight);TheContext.stroke();TheContext.beginPath();TheContext.moveTo(CloseBoxWidth,0);TheContext.lineTo(0,CloseBoxHeight);TheContext.stroke();TheContext.strokeRect(1,1,CloseBoxWidth-2,CloseBoxHeight-2);}
function CMDialog(ID,Width,Height,PageDisabled){if(Width==-1)Width=CMDialog.DIALOG_WIDTH;if(Height==-1)Height=CMDialog.DIALOG_HEIGHT;this.TheElement=document.getElementById(ID);if(this.TheElement==null){this.TheElement=document.createElement("DIV");this.TheElement.id=ID;document.body.appendChild(this.TheElement);}else{while(this.TheElement.firstChild){this.TheElement.removeChild(this.TheElement.firstChild);}}this.TheElement.className="CM_SettingsDialog";this.TheElement.style.visibility="visible";var DocumentHeight=$(window).height();var DocumentWidth=$(window).width();var X=(DocumentWidth-Width)/2;var Y=(DocumentHeight-Height)/2;CMUtilities.AbsolutePosition(this.TheElement,X,Y,Width,Height);var CloseBox=CMDialog.CreateCloseBox(this,Width-26,10,16,16,"#ffffff");var DisablePageID="DialogDisablePage"
this.DisablePage=document.getElementById(DisablePageID);if(this.DisablePage==null){this.DisablePage=document.createElement("DIV");this.DisablePage.id=DisablePageID;document.body.appendChild(this.DisablePage);}this.DisablePage.style.visibility="hidden";if(PageDisabled){this.DisablePage.style.backgroundColor="white";this.DisablePage.style.visibility="visible"
this.DisablePage.style.opacity="0.5";this.DisablePage.style.zIndex="99999999";var DocumentHeight=$(window).height();var DocumentWidth=$(window).width();X=0;Y=0;CMUtilities.AbsolutePosition(this.DisablePage,X,Y,DocumentWidth,DocumentHeight);}}CMDialog.prototype.SetVisible=function(New){if(New){this.TheElement.style.visibility="visible";this.DisablePage.style.visibility="visible";}else{this.TheElement.style.visibility="hidden";this.DisablePage.style.visibility="hidden";}}
CMDialog.AddLabelToPanel=function(TheElement,Text,XOffset,YPosition){var Label=document.createElement("div");Label.innerHTML=Text;TheElement.appendChild(Label);CMUtilities.AbsolutePosition(Label,XOffset+10,YPosition,300,30);return(Label);}
CMDialog.AddParagraphToPanel=function(TheElement,Text,XOffset,YPosition,Width,Height){var TheControl=document.createElement("p");TheControl.innerHTML=Text;TheElement.appendChild(TheControl);CMUtilities.AbsolutePosition(TheControl,XOffset+10,YPosition,Width,Height);return(TheControl);}
CMDialog.AddColorControlToPanel=function(TheElement,Label,XOffset,YPosition,Value){var PenColorLabel=document.createElement("div");PenColorLabel.innerHTML=Label;TheElement.appendChild(PenColorLabel);CMUtilities.AbsolutePosition(PenColorLabel,XOffset+10,YPosition,100,30);var PenColorControl=document.createElement("input");var ColorControlContainer=document.createElement("div");ColorControlContainer.innerHTML="<input id='ColorControl' type='color'>";var PenColorControl=ColorControlContainer.childNodes[0];Value=CMUtilities.GetHexColorFromColor(Value);PenColorControl.value=Value;TheElement.appendChild(PenColorControl);CMUtilities.AbsolutePosition(PenColorControl,XOffset+110,YPosition,100,20);return(PenColorControl);}
CMDialog.AddButtonControlToPanel=function(TheElement,Text,XOffset,YPosition){var OKButton=document.createElement("button");var ButtonText=document.createTextNode(Text);OKButton.appendChild(ButtonText);TheElement.appendChild(OKButton);CMUtilities.AbsolutePosition(OKButton,XOffset+10,YPosition,80,30);return(OKButton);}
CMDialog.AddSliderControlToPanel=function(TheElement,Text,XOffset,YPosition,Min,Max,Value){var PenColorLabel=CMUtilities.CreateLabelControl(Text);CMUtilities.AbsolutePosition(PenColorLabel,XOffset+10,YPosition,80,30);TheElement.appendChild(PenColorLabel);var SliderControl=CMUtilities.CreateSliderControl(Min,Max,Value);CMUtilities.AbsolutePosition(SliderControl,XOffset+110,YPosition,100,30);TheElement.appendChild(SliderControl);return(SliderControl);}
CMDialog.AddCheckBoxControlToPanel=function(TheElement,Text,XOffset,YPosition,Value){var TheControl=document.createElement("input");TheControl.type="checkbox";TheControl.name=Text;TheControl.text=Text;if(Value)TheControl.checked=true;else TheControl.checked=false;TheElement.appendChild(TheControl);CMUtilities.AbsolutePosition(TheControl,XOffset,YPosition,40,30);var TheLabel=document.createElement("div");TheLabel.innerHTML=Text;TheElement.appendChild(TheLabel);CMUtilities.AbsolutePosition(TheLabel,XOffset+60,YPosition+8,80,30);return(TheControl);}
CMDialog.AddTextControlToPanel=function(TheElement,Text,XOffset,YPosition,Value){var TheLabel=document.createElement("div");TheLabel.innerHTML=Text;TheElement.appendChild(TheLabel);CMUtilities.AbsolutePosition(TheLabel,XOffset+10,YPosition+8,100,30);var TheControl=document.createElement("input");TheControl.type="text";TheControl.name=Text;if(Value!=undefined)TheControl.value=Value;TheElement.appendChild(TheControl);CMUtilities.AbsolutePosition(TheControl,XOffset+110,YPosition,80,24);return(TheControl);}
CMDialog.AddRadioControlToPanel=function(TheElement,Name,XOffset,YPosition,Values,Selected){var Result=[];for(var i=0;i<Values.length;i++){var TheControl=document.createElement("input");TheControl.type="radio";TheControl.name=Name;TheControl.value=Values[i];if(Selected==Values[i]){TheControl.checked=true;}TheElement.appendChild(TheControl);CMUtilities.AbsolutePosition(TheControl,XOffset+10,YPosition,24,24);var TheLabel=document.createElement("div");TheLabel.innerHTML=Values[i];TheElement.appendChild(TheLabel);CMUtilities.AbsolutePosition(TheLabel,XOffset+50,YPosition+8,100,30);YPosition+=30;Result.push(TheControl);}return(Result);}
CMDialog.AddSelectControlToPanel=function(TheElement,Name,XOffset,YPosition,Values,Selected){var Result=[];var SelectedIndex=-1;var TheLabel=document.createElement("div");TheLabel.innerHTML=Name;TheElement.appendChild(TheLabel);CMUtilities.AbsolutePosition(TheLabel,XOffset+10,YPosition+8,100,30);var TheControl=CMUtilities.CreateSelectControl(Values,Selected);TheControl.name=Name;TheElement.appendChild(TheControl);CMUtilities.AbsolutePosition(TheControl,XOffset+110,YPosition,150,24);return(TheControl);}
CMDialog.prototype.AddLabel=function(Text,XOffset,YPosition){var Label=CMDialog.AddLabelToPanel(this.TheElement,Text,XOffset,YPosition);return(Label);}
CMDialog.prototype.AddParagraph=function(Text,XOffset,YPosition,Width,Height){var TheControl=CMDialog.AddParagraphToPanel(this.TheElement,Text,XOffset,YPosition,Width,Height);return(TheControl);}
CMDialog.prototype.AddColorControl=function(Label,XOffset,YPosition,Value){var PenColorControl=CMDialog.AddColorControlToPanel(this.TheElement,Label,XOffset,YPosition,Value);return(PenColorControl);}
CMDialog.prototype.AddButtonControl=function(Text,XOffset,YPosition){var OKButton=CMDialog.AddButtonControlToPanel(this.TheElement,Text,XOffset,YPosition);return(OKButton);}
CMDialog.prototype.AddSliderControl=function(Text,XOffset,YPosition,Min,Max,Value){var SliderControl=CMDialog.AddSliderControlToPanel(this.TheElement,Text,XOffset,YPosition,Min,Max,Value);return(SliderControl);}
CMDialog.prototype.AddCheckBoxControl=function(Text,XOffset,YPosition,Value){var TheControl=CMDialog.AddCheckBoxControlToPanel(this.TheElement,XOffset,YPosition,Value);return(TheControl);}
CMDialog.prototype.AddTextControl=function(Text,XOffset,YPosition,Value){var TheControl=CMDialog.AddTextControlToPanel(this.TheElement,Text,XOffset,YPosition,Value)
return(TheControl);}
CMDialog.prototype.AddRadioControl=function(Name,XOffset,YPosition,Values,Selected){var Result=CMDialog.AddRadioControlToPanel(this.TheElement,Name,XOffset,YPosition,Values,Selected)
return(Result);}
CMDialog.prototype.AddSelectControl=function(Name,XOffset,YPosition,Values,Selected){var TheControl=CMDialog.AddSelectControlToPanel(this.TheElement,Name,XOffset,YPosition,Values,Selected);return(TheControl);}
CMDialog.GetRGBAFromControls=function(FillColorControl,FillTransparencyControl){var Transparency=FillTransparencyControl.value;var Color=FillColorControl.value;var Colors=CMUtilities.GetRGBFromHex(Color);var RGBA=Colors.Red+","+Colors.Green+","+Colors.Blue;if(Transparency!=100){Transparency=Transparency/100;RGBA="rgba("+RGBA+","+Transparency+")";;}else{RGBA="rgb("+RGBA+")";;}return(RGBA);}