CMItem.SettingDefintions={Style:{strokeStyle:{Name:"Line Style",Type:CMBase.DATA_TYPE_CSS_STYLE,Default:"rgb(0,0,0)"},lineWidth:{Name:"Line Width",Type:CMBase.DATA_TYPE_INTEGER,Default:1},lineCap:{Name:"Line Cap",Type:CMBase.DATA_TYPE_ENUMERATED,Options:['butt','round','square'],Default:'round'},lineJoin:{Name:"Line Join",Type:CMBase.DATA_TYPE_ENUMERATED,Options:['bevel','round','miter'],Default:'round'},fillStyle:{Name:"Fill Style",Type:CMBase.DATA_TYPE_CSS_STYLE,Default:"rgb(255,255,255)"},shadowColor:{Name:"Shadow Color",Type:CMBase.DATA_TYPE_COLOR,Default:"rgb(0,0,0)"},shadowBlur:{Name:"Shadow Blur",Type:CMBase.DATA_TYPE_FLOAT,Default:1},shadowOffsetX:{Name:"Shadow X",Type:CMBase.DATA_TYPE_FLOAT,Default:1},shadowOffsetY:{Name:"Shadow Y",Type:CMBase.DATA_TYPE_FLOAT,Default:1}},Text:{Text:{Name:"Text",Type:CMBase.DATA_TYPE_STRING,Default:null},font:{Name:"Font",Type:CMBase.DATA_TYPE_FONT,Default:"12px Arial"},strokeStyle:{Name:"Line Style",Type:CMBase.DATA_TYPE_CSS_STYLE,Default:"rgb(0,0,0)"},fillStyle:{Name:"Fill Style",Type:CMBase.DATA_TYPE_CSS_STYLE,Default:"rgb(255,255,255)"},lineWidth:{Name:"Width",Type:CMBase.DATA_TYPE_INTEGER,Default:1},lineCap:{Name:"Line Cap",Type:CMBase.DATA_TYPE_ENUMERATED,Options:['butt','round','square'],Default:'round'},lineJoin:{Name:"Line Join",Type:CMBase.DATA_TYPE_ENUMERATED,Options:['bevel','round','miter'],Default:'round'}},};CMItem.UniqueNumber=0;function CMItem(){CMBase.call(this);this.UniqueNumber=CMItem.UniqueNumber;this.TimeSlices=[{UniqueNumber:CMItem.UniqueNumber,Time:0,Settings:{Style:{strokeStyle:"rgb(0,0,0)",lineWidth:1,fillStyle:"rgb(255,255,255)"},Text:{},}}];CMItem.UniqueNumber++;this.LastStyle=null;this.LastTimeSlice=0;}CMItem.prototype=Object.create(CMBase.prototype);CMItem.prototype.contructor=CMItem;CMItem.prototype.GetSettingsDefinitions=function(){var Result={};for(Key in CMItem.SettingDefintions){Result[Key]=CMItem.SettingDefintions[Key];}return(Result);}
CMItem.prototype.GetSettings=function(TimeSlice){var Result=null;var TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){Result=this.TimeSlices[TimeSliceIndex].Settings;}return(Result);}
CMItem.prototype.SetSettings=function(NewSettings,TimeSlice){var TimeSliceIndex=0;if(TimeSlice!=undefined)TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){this.TimeSlices[TimeSliceIndex].Settings=NewSettings;}this.LastStyle=null;this.Repaint();}
CMItem.prototype.SetSettingGroup=function(Group,Values,TimeSlice){var TimeSliceIndex=0;if(TimeSlice!=undefined)TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){this.TimeSlices[TimeSliceIndex].Settings[Group]=Values;}this.LastStyle=null;this.Repaint();}
CMItem.prototype.GetSettingGroup=function(Group,Default,TimeSlice){var Result=null;if(Default!=undefined)Result=Default;var TimeSliceIndex=0;if(TimeSlice!=undefined)TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){Result=this.TimeSlices[TimeSliceIndex].Settings[Group];}return(Result);}
CMItem.prototype.SetSetting=function(Group,Key,Value,TimeSlice){var TimeSliceIndex=0;if(TimeSlice!=undefined)TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){var TheSettings=this.TimeSlices[TimeSliceIndex].Settings;TheSettings[Group][Key]=Value;}this.LastStyle=null;this.Repaint();}
CMItem.prototype.GetSetting=function(Group,Key,Default,TimeSlice){var Result=null;if(Default!=undefined)Result=Default;var TimeSliceIndex=0;if(TimeSlice!=undefined)TimeSliceIndex=CMItem.FindTimeSliceIndex(this.TimeSlices,TimeSlice);if(TimeSliceIndex!=-1){var TheGroup=this.TimeSlices[TimeSliceIndex].Settings[Group];if(TheGroup!=undefined){if(Key in TheGroup)Result=TheGroup[Key];}}return(Result);}
CMItem.prototype.UnselectAll=function(SendMessageFlag){if(this.Selected){this.Selected=false;if(SendMessageFlag){var TheScene=this.GetParent(CMScene);TheScene.SelectionChanged(this);}}}
CMItem.prototype.GetSelected=function(){return(this.Selected);}
CMItem.prototype.SetSelected=function(New){if(this.Selected!=New){var TheScene;if(this instanceof CMScene){TheScene=this;}else{TheScene=this.GetParent(CMScene);}if(New){TheScene.UnselectAll(false);this.Selected=true;TheScene.SelectionChanged(this);}else{this.Selected=false;TheScene.SelectionChanged(this);}}}
CMItem.FindTimeSliceIndex=function(TimeSliceSettings,TimeSlice){var Result=-1;if(TimeSlice==undefined){if(TimeSliceSettings.length>0)Result=0;}else{for(var i=0;(i<TimeSliceSettings.length)&&(Result==-1);i++){var TimeSliceSetting=TimeSliceSettings[i];if(TimeSliceSetting.Time==TimeSlice)Result=i;}}return(Result);}
CMItem.prototype.GetTimes=function(TheTimeSlices){TheTimeSlices=[];for(var i=0;i<this.TimeSlices.length;i++){var Time=this.TimeSlices[i].Time;CMUtilities.InsertIntoSortedArray(TheTimeSlices,parseFloat(Time));}return(TheTimeSlices);}
CMItem.prototype.InsertTime=function(Time){var TimeSlices=this.TimeSlices;var Index=-1;for(var i=0;i<TimeSlices.length;i++){if(TimeSlices[i].Time==Time){Index=i;}else if(TimeSlices[i].Time>Time){Index=i;TimeSlices.splice(Index,0,Time);}}if(Index==-1){Index=TimeSlices.length;TimeSlices.push({Settings:{},Time:Time});}if(Index!=-1){var OldTimeSliceSettings=TimeSlices[Index-1].Settings;var NewTimeSliceSettings=TimeSlices[Index].Settings;for(ClassKey in OldTimeSliceSettings){var TheSetting=OldTimeSliceSettings[ClassKey];TheSetting=CMUtilities.Clone(TheSetting);NewTimeSliceSettings[ClassKey]=TheSetting;}}this.Repaint();return(Index);}
CMItem.prototype.DeleteTime=function(Time){var TimeSlices=this.TimeSlices;var Index=-1;for(var i=0;i<TimeSlices.length;i++){if(TimeSlices[i].Time==Time){Index=i;TimeSlices.splice(Index,1);}}this.Repaint();return(Index);}
CMItem.GetTimeFactor=function(TimeSliceArray){var TimeSlice1=TimeSliceArray[0].Time;var TimeSlice2=TimeSliceArray[1].Time;var Range=TimeSlice2-TimeSlice1;var Factor=(Range-TimeSlice)/Range;return(Factor);}
CMItem.GetTweenFloatValue=function(Value1,Value2,Default,Factor){var Result=Default;if(Value1!=undefined){if(Value2!=undefined){Result=(Value1*Factor)+(Value2*(1-Factor));}else{Result=Value1;}}else if(Value2!=undefined){Result=Value2;}return(Result);}
CMItem.GetTweenColorValue=function(Value1,Value2,Default,Factor){var Result=Default;var Colors=null;if(Value1!=undefined){var Colors1=CMUtilities.GetColorsFromAnyColor(Value1);if(Value2!=undefined){var Colors2=CMUtilities.GetColorsFromAnyColor(Value2);Colors={Red:Math.round((Colors1.Red*Factor)+(Colors2.Red*(1-Factor))),Green:Math.round((Colors1.Green*Factor)+(Colors2.Green*(1-Factor))),Blue:Math.round((Colors1.Blue*Factor)+(Colors2.Blue*(1-Factor)))}}else{Colors=Value1;}}else if(Value2!=undefined){Colors=Value2;}if(Colors!=null)Result="rgb("+Colors.Red+","+Colors.Green+","+Colors.Blue+")";return(Result);}
CMItem.GetTweenStyleValue=function(Value1,Value2,Default,Factor){var Result=CMItem.GetTweenColorValue(Value1,Value2,Default,Factor);return(Result);}
CMItem.prototype.GetBoundingTimeSlices=function(TimeSlice){if(TimeSlice==undefined){var TheScene=this.GetParent(CMScene);TimeSlice=TheScene.GetTimeRange();}var TheTimeSliceSetting1=null;var TheTimeSliceSetting2=null;for(var i=0;(i<this.TimeSlices.length)&&(TheTimeSliceSetting1==null);i++){var ThisSlicesTime=parseFloat(this.TimeSlices[i].Time);if(ThisSlicesTime==TimeSlice){TheTimeSliceSetting1=this.TimeSlices[i];}else if(ThisSlicesTime>TimeSlice){if(i==0){TheTimeSliceSetting1=this.TimeSlices[0];}else{TheTimeSliceSetting1=this.TimeSlices[i-1];TheTimeSliceSetting2=this.TimeSlices[i];}}}if((TheTimeSliceSetting1==null)&&(this.TimeSlices.length>0)){TheTimeSliceSetting1=this.TimeSlices[this.TimeSlices.length-1];}var Result=[TheTimeSliceSetting1,TheTimeSliceSetting2];return(Result);}
CMItem.prototype.GetStyle=function(TheView,TimeSlice,Group){if(TimeSlice==undefined)TimeSlice=0;if(Group==undefined)Group="Style";{this.LastStyle=null;this.LastTimeSlice=TimeSlice;var Result=this.GetBoundingTimeSlices(TimeSlice);var TheTimeSlice1=Result[0];var TheTimeSliceSetting1=TheTimeSlice1.Settings;var TheTimeSlice2=Result[1];if(TheTimeSlice1!=null){var TheStyle;if(TheTimeSlice2==null){{var TheGroup1=TheTimeSliceSetting1[Group];for(TheSettingKey1 in TheGroup1){if(TheStyle===undefined)TheStyle={};var TheSetting1=TheGroup1[TheSettingKey1];TheStyle[TheSettingKey1]=TheSetting1;}}}else{var TheTimeSliceSetting2=TheTimeSlice2.Settings;var Factor=CMItem.GetTimeFactor(Result);{var TheGroup1=TheTimeSliceSetting1[Group];var TheGroup2=TheTimeSliceSetting2[Group];for(TheSettingKey1 in TheGroup1){if(TheStyle===undefined)TheStyle={};var TheSetting1=TheGroup1[TheSettingKey1];var TheSetting2=TheGroup2[TheSettingKey1];if((TheSettingKey1=="strokeStyle")||(TheSettingKey1=="fillStyle")){TheStyle[TheSettingKey1]=CMItem.GetTweenStyleValue(TheSetting1,TheSetting2,"rgb(0,0,0)",Factor);}else if(TheSettingKey1=="shadowColor"){TheStyle[TheSettingKey1]=CMItem.GetTweenColorValue(TheSetting1,TheSetting2,"rgb(0,0,0)",Factor);}else{TheStyle[TheSettingKey1]=CMItem.GetTweenFloatValue(TheSetting1,TheSetting2,0,Factor);}}}}for(key in TheStyle){if((key=="lineWidth")||(key=="shadowOffsetX")||(key=="shadowOffsetY")||(key=="shadowBlur")){var Test=12;}}this.LastStyle=TheStyle;}}return(this.LastStyle);}
CMItem.prototype.ResetStyle=function(){}
CMItem.prototype.Repaint=function(){var Result=this.GetParent(CMScene);if(Result!=null)Result.Repaint();}
CMItem.prototype.Paint=function(TheView){}
CMItem.prototype.PaintSelected=function(TheView){}
CMItem.prototype.SetVisible=function(Flag){if(this.Visible!=Flag){this.Visible=Flag;this.Repaint();}}
CMItem.prototype.GetVisible=function(){if(this.Visible==undefined)this.Visible=true;return(this.Visible);}