function CMLayerDataset(){CMLayer.call(this);this.TheDataset=null;}CMLayerDataset.prototype=Object.create(CMLayer.prototype);CMLayerDataset.prototype.contructor=CMLayerDataset;CMLayerDataset.prototype.CMLayer_SetParent=CMLayer.prototype.SetParent;CMLayerDataset.prototype.SetParent=function(NewParent){this.CMLayer_SetParent(NewParent);if(this.TheDataset!=null)this.TheDataset.SetParent(this.GetParent(CMScene));}
CMLayerDataset.prototype.CMLayer_UnselectAll=CMLayer.prototype.UnselectAll;CMLayerDataset.prototype.UnselectAll=function(SendMessageFlag){this.CMLayer_UnselectAll(SendMessageFlag);if((this.TheDataset!=null)&&(this.TheDataset.GetSelectedFeature()!=-1)){this.TheDataset.SetSelectedFeature(-1);if(SendMessageFlag){var TheScene=this.GetParent(CMScene);TheScene.SelectionChanged(this);}}}
CMLayerDataset.prototype.Paint=function(TheView){if((this.IsVisible())&&(this.TheDataset!=null)){var TheStyle=this.GetStyle(TheView);if(TheStyle!==null){TheView.SetStyle(TheStyle);}this.TheDataset.Paint(this,TheView,false);if(TheStyle!==null){TheView.RestoreStyle();}}}
CMLayerDataset.prototype.PaintSelected=function(TheView){if((this.IsVisible())&&(this.TheDataset!=null)){var TheStyle=this.GetStyle(TheView,undefined,"MouseOverStyle");if(CMUtilities.IsDefined(TheStyle)){TheView.SetStyle(TheStyle);this.TheDataset.Paint(this,TheView,false,true);TheView.RestoreStyle();}var TheStyle=this.GetStyle(TheView,undefined,"SelectedStyle");if(CMUtilities.IsDefined(TheStyle)){TheView.SetStyle(TheStyle);this.TheDataset.Paint(this,TheView,true);TheView.RestoreStyle();}}}
CMLayerDataset.prototype.SetBounds=function(NewBounds){if(this.GetDataset()!=undefined){this.GetDataset().SetBounds(NewBounds);var TheScene=this.GetParent(CMScene);TheScene.SetBoundsDirty();}}
CMLayerDataset.prototype.GetBounds=function(){var TheBounds=undefined;if(this.GetDataset()!=undefined){TheBounds=this.GetDataset().GetBounds();}return(TheBounds);}
CMLayerDataset.prototype.CMLayer_SettingsChanged=CMLayerDataset.prototype.SettingsChanged;CMLayerDataset.prototype.SettingsChanged=function(){this.CMLayer_SettingsChanged();if(this.SettingsDirty){if(this.SettingsAttributes!=null){var TheDataset=this.GetDataset();for(var SettingsGroupKey in this.SettingsAttributes){var SettingsGroup=this.SettingsAttributes[SettingsGroupKey];for(var SettingsKey in SettingsGroup){var AttributeName=SettingsGroup[SettingsKey];for(var j=0;j<TheDataset.GetNumAttributeRows();j++){var Value=TheDataset.GetAttributeCellByHeading(AttributeName,j);if((Value!==undefined)&&(Value!=="")){if((SettingsGroupKey=="IconImage")&&(SettingsKey=="URL")){var TheImage;TheImage=new Image();TheImage.Loaded=false;TheImage.TheLayer=this;TheImage.onload=function(){this.Loaded=true;this.TheLayer.Repaint();};TheImage.src=Value;}else if((SettingsGroupKey=="Mark")&&(SettingsKey=="Type")){if(Value==="MARK_CIRCLE")Value=CMLayer.MARK_CIRCLE;if(Value==="MARK_TRIANGLE")Value=CMLayer.MARK_TRIANGLE;if(Value==="MARK_SQUARE")Value=CMLayer.MARK_SQUARE;if(Value==="MARK_STAR")Value=CMLayer.MARK_STAR;}else if((SettingsGroupKey=="Mark")&&(SettingsKey=="Size")){Value=parseInt(Value);}else{Value=Value;}this.SetFeatureSetting(SettingsGroupKey,SettingsKey,j,Value);}}}}this.Repaint();this.SettingsDirty=false;}}}
CMLayerDataset.prototype.SetProjector=function(NewProjector){if(this.TheDataset!=null){this.TheDataset.SetProjector(NewProjector);}}
CMLayerDataset.prototype.SetSelectedFeature=function(New){if((this.TheDataset!=null)&&(New!=this.TheDataset.GetSelectedFeature())){this.TheDataset.SetSelectedFeature(New);var TheScene=this.GetParent(CMScene);TheScene.SelectionChanged(this);}}
CMLayerDataset.prototype.SetMouseOverFeature=function(New){if((this.TheDataset!=null)&&(this.TheDataset.GetMouseOverFeature()!=New)){this.TheDataset.SetMouseOverFeature(New);}}
CMLayerDataset.prototype.ResetMouseOverFeature=function(){if((this.TheDataset!=null)&&(this.TheDataset.GetMouseOverFeature()!=-1)){this.TheDataset.SetMouseOverFeature(-1);}}
CMLayerDataset.prototype.In=function(TheView,RefX,RefY){var FeatureIndex=-1;if(this.TheDataset!=null){var NumFeatures=this.TheDataset.GetNumFeatures();for(var i=0;(i<NumFeatures)&&(FeatureIndex==-1);i++){if(this.TheDataset.InFeature(TheView,RefX,RefY,i)){if(this.IsFeatureVisible(i))FeatureIndex=i;}}}return(FeatureIndex);};CMLayerDataset.prototype.GetSearchResults=function(SearchPhrase,ResultsPanel){if(this.TheDataset!=null){this.TheDataset.GetSearchResults(SearchPhrase,ResultsPanel);}}
CMLayerDataset.prototype.CMLayer_GetIcon=CMLayer.prototype.GetIcon;CMLayerDataset.prototype.GetIcon=function(){var TheIcon=this.CMLayer_GetIcon();if(this.TheDataset!=null){TheIcon=this.TheDataset.GetIcon(this,TheIcon);}return(TheIcon);}
CMLayerDataset.prototype.SetURL=function(URL,ZoomToBounds,DataSetType,TheProjector){var TheScene=this.GetParent(CMScene);this.TheDataset=CMDataset.GetDataObject(URL,DataSetType);this.TheDataset.SetParent(TheScene);this.TheDataset.AddListener(CMDataset.MESSAGE_DATASET_LOADED,this,function(TheDataset,ThisLayer,AdditionalInfo){ThisLayer.OnLoad();ThisLayer.GetScene().LayerListChanged();});this.TheDataset.AddListener(CMDataset.MESSAGE_DATASET_SELECTION_CHANGED,this,function(TheDataset,ThisLayer,AdditionalInfo){ThisLayer.GetScene().Repaint();});this.TheDataset.AddListener(CMDataset.MESSAGE_DATASET_MOUSE_OVER_FEATURE_CHANGED,this,function(TheDataset,ThisLayer,AdditionalInfo){ThisLayer.GetScene().Repaint();});if(TheProjector!=undefined)this.TheDataset.SetProjector(TheProjector);this.TheDataset.SetURL(URL,ZoomToBounds);}
CMLayerDataset.prototype.SetData=function(TheData,ZoomToBounds,DataSetType,TheProjector){var TheScene=this.GetParent(CMScene);this.TheDataset=CMDataset.GetDataObject(URL,DataSetType);this.TheDataset.SetParent(TheScene);this.TheDataset.AddListener(CMDataset.MESSAGE_DATASET_LOADED,this,function(TheDataset,ThisLayer,AdditionalInfo){ThisLayer.OnLoad();});if(TheProjector!=undefined)this.TheDataset.SetProjector(TheProjector);this.TheDataset.SetData(TheData);};CMLayerDataset.prototype.GetDataset=function(){return(this.TheDataset);};CMLayerDataset.prototype.SetDataset=function(NewDataset){this.TheDataset=NewDataset;};CMLayerDataset.prototype.AddPoint=function(X,Y){if(this.TheDataset!=null){this.TheDataset.AddPoint(X,Y);}else{alert("Sorry, a dataset must be set before we can add points to a layer");}}