function CMPanelTool(TheCanvasMap){CMBase.call(this);if(TheCanvasMap==undefined)alert("Sorry, the CMPanelTool requires a CanvasMap object on construction");this.SetParent(TheCanvasMap);this.Tools=[];}CMPanelTool.prototype=Object.create(CMBase.prototype);CMPanelTool.prototype.contructor=CMPanelTool;CMPanelTool.prototype.GetToolIndexFromID=function(ToolID){var Result=-1;for(var i=0;i<this.Tools.length;i++){if(this.Tools[i].id==ToolID)Result=i;}return(Result);}
CMPanelTool.prototype.SetElement=function(TheElement){this.TheElement=TheElement;this.Tools=[];}
CMPanelTool.prototype.AddTool=function(ToolElement,UnselectedFilePath,SelectedFilePath,TheHandler,ToolTip,TheFunction){if(this.TheElement!=null){var ToolID;if(typeof(ToolElement)==='string'){var ToolID=ToolElement;ToolElement=document.createElement("DIV");ToolElement.id=ToolID;ToolElement.className="CM_Tool";}else{ToolID=ToolElement.id;}ToolElement.style.backgroundColor="none";ToolElement.title=ToolTip;ToolElement.cursor='pointer';ToolElement.innerHTML="<img id='"+ToolID+"_Image' class='CMTool_Image' \
		  src='"+UnselectedFilePath+"'alt='ID Marker'>";ToolElement.Selected=false;ToolElement.ToolPanel=this;ToolElement.UnselectedFilePath=UnselectedFilePath;ToolElement.SelectedFilePath=SelectedFilePath;ToolElement.TheFunction=TheFunction;ToolElement.onclick=function(){var TheToolPanel=this.ToolPanel;var TheCanvasMap=TheToolPanel.GetParent(CMMainContainer);TheToolPanel.SelectTool(this.id);CMMainContainer.HidePopupWindow();if(this.TheFunction!=undefined){this.TheFunction(TheHandler);}}
this.TheElement.appendChild(ToolElement);this.Tools.push(ToolElement);}return(ToolElement);}
CMPanelTool.prototype.MakeToolGroup=function(ToolArray){for(var i=0;i<ToolArray.length;i++){var ToolElement=ToolArray[i];ToolElement.parentNode.removeChild(ToolElement);}var TheTableDIV=document.createElement("DIV");TheTableDIV.className="CM_ToolGroup";var TheTable=document.createElement("TABLE");TheTableDIV.appendChild(TheTable);TheTable.style.borderSpacing="0px";var TheRow=TheTable.insertRow(0);var TheTableWidth=0;for(var i=0;i<ToolArray.length;i++){var ToolElement=ToolArray[i];ToolElement.className="CM_ToolInGroup";var TheCell=TheRow.insertCell(-1);if(i!=ToolArray.length-1)TheCell.style.borderRight="thin solid #999";TheCell.appendChild(ToolElement);TheTableWidth+=28;}TheTableDIV.style.width=TheTableWidth+"px";this.TheElement.appendChild(TheTableDIV);return(TheTableDIV);}
CMPanelTool.prototype.RemoveToolGroupElement=function(ToolGroupElement){this.TheElement.removeChild(ToolGroupElement);}
CMPanelTool.prototype.AddToolGroupElement=function(ToolGroupElement){this.TheElement.appendChild(ToolGroupElement);}
CMPanelTool.prototype.RemoveTool=function(ToolID){var Index=this.GetToolIndexFromID(ToolID);if(Index!=-1){var ToolElement=this.Tools[Index];ToolElement.parentNode.removeChild(ToolElement);this.Tools.splice(Index,1);}}
CMPanelTool.prototype.SelectTool=function(TargetToolID){for(var i=0;i<this.Tools.length;i++){var TheElement=this.Tools[i];if(TheElement.id==TargetToolID){TheElement.Selected=true;var ImageElement=document.getElementById(TargetToolID+"_Image");ImageElement.src=TheElement.SelectedFilePath;}else{if(TheElement.Selected){if(TheElement.UnselectFunction!=undefined)TheElement.UnselectFunction();TheElement.Selected=false;var ImageElement=document.getElementById(TheElement.id+"_Image");ImageElement.src=TheElement.UnselectedFilePath;}}}}