CMScene.MESSAGE_LAYER_LIST_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_LAYER_CONTENT_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_LAYER_SETTINGS_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_BACKGROUNDS_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_TIME_SLICES_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_TIME_RANGE_CHANGED=CMBase.GetUniqueNumber();CMScene.MESSAGE_SELECTION_CHANGED=CMBase.GetUniqueNumber();CMScene.SettingDefintions={Fill:{fillStyle:{Name:"Style",Type:CMBase.DATA_TYPE_CSS_STYLE,Default:"rgb(255,255,255)"},}};function CMScene(TheCanvasMap){CMItem.call(this);this.SetParent(TheCanvasMap);this.Views=[];this.Layers=[];this.Backgrounds=[];this.SelectedBackgroundIndex=-1;this.MapElements=[];this.TimeSlices=[{Time:0,Settings:{Fill:{fillStyle:"rgb(210,220,255)"},}}];this.TheProjector=null;this.MinTime=0;this.Times=[0];this.TheBounds=null;this.NumRepaintBlocks=0;this.NeedRepaint=false;}CMScene.prototype=Object.create(CMItem.prototype);CMScene.prototype.contructor=CMScene;CMScene.prototype.GetView=function(ViewIndex){var Result=null;Result=this.Views[ViewIndex];return(Result);}
CMScene.prototype.GetNumViews=function(){var Result=this.Views.length;return(Result);}
CMScene.prototype.GetCanvasMap=function(){var Result=this.GetParent(CMMainContainer);return(Result);}
CMScene.prototype.GetTimes=function(TheTimeSlices){return(this.Times);}
CMScene.prototype.AddBackground=function(TheLayer){if(this.SelectedBackgroundIndex==-1)this.SelectedBackgroundIndex=0;TheLayer.SetParent(this);var LayerIndex=this.Backgrounds.length;this.Backgrounds[LayerIndex]=TheLayer;this.SendMessageToListeners(CMScene.MESSAGE_BACKGROUNDS_CHANGED);return(LayerIndex);}
CMScene.prototype.SetSelectedBackgroundIndex=function(New){if(this.SelectedBackgroundIndex!=-1){this.Backgrounds[this.SelectedBackgroundIndex].SetVisible(false);}this.SelectedBackgroundIndex=New;if(New!=-1){this.Backgrounds[New].SetVisible(true);}this.Repaint();}
CMScene.prototype.GetSettingsDefinitions=function(){var Result={};for(Key in CMScene.SettingDefintions){Result[Key]=CMScene.SettingDefintions[Key];}return(Result);}
CMScene.prototype.AddLayer=function(TheLayer){TheLayer.SetParent(this);var LayerIndex=this.Layers.length;this.Layers[LayerIndex]=TheLayer;var NewTimes=TheLayer.GetTimes(this.Times);for(Time in NewTimes){var Index=this.Times.indexOf(Time);if(Index==-1){this.InsertTime(Time);}}this.LayerListChanged();return(LayerIndex);}
CMScene.prototype.GetNumLayers=function(){return(this.Layers.length);}
CMScene.prototype.GetLayer=function(Index){return(this.Layers[Index]);}
CMScene.prototype.GetLayerIndex=function(TheLayer){var Result=-1;for(var i=0;i<this.Layers.length;i++){if(this.Layers[i]==TheLayer)Result=i;}return(Result);}
CMScene.prototype.MoveLayerUp=function(Index){var TheLayer=this.Layers[Index];if(Index>=0){this.Layers[Index]=this.Layers[Index-1];this.Layers[Index-1]=TheLayer;}this.LayerListChanged();this.Repaint();}
CMScene.prototype.MoveLayerDown=function(Index){var TheLayer=this.Layers[Index];if(Index<this.Layers.length){this.Layers[Index]=this.Layers[Index+1];this.Layers[Index+1]=TheLayer;}this.LayerListChanged();this.Repaint();}
CMScene.prototype.DeleteLayer=function(Index){var Result=this.Layers.splice(Index,1);this.LayerListChanged();this.Repaint();return(Result);}
CMScene.prototype.MoveLayer=function(TheLayer,NewIndex){var CurrentIndex=this.GetLayerIndex(TheLayer);if(NewIndex<0)NewIndex=0;if(NewIndex>=this.Layers.length)NewIndex=this.Layers.length-1;if(NewIndex<CurrentIndex){for(var i=CurrentIndex;i>NewIndex;i--){this.Layers[i]=this.Layers[i-1];}this.Layers[NewIndex]=TheLayer;}else if(NewIndex>CurrentIndex){for(var i=CurrentIndex;i<NewIndex;i++){this.Layers[i]=this.Layers[i+1];}this.Layers[NewIndex]=TheLayer;}this.LayerListChanged();this.Repaint();}
CMScene.prototype.GetSearchResults=function(TheText,SearchResults){for(var i=0;i<this.Layers.length;i++){this.Layers[i].GetSearchResults(TheText,SearchResults);}}
CMScene.prototype.AddMapElement=function(TheElement){this.MapElements.push(TheElement);TheElement.SetParent(this);}
CMScene.prototype.AddView=function(TheView){TheView.SetParent(this);var ViewIndex=this.Views.length;this.Views[ViewIndex]=TheView;this.SetTimeRange(0);}
CMScene.prototype.ViewMoved=function(TheView){for(var i=0;i<this.Backgrounds.length;i++){this.Backgrounds[i].ViewMoved(TheView);}for(var i=0;i<this.Layers.length;i++){this.Layers[i].ViewMoved(TheView);}for(var i=0;i<this.MapElements.length;i++){this.MapElements[i].ViewMoved(TheView);}}
CMScene.prototype.SetTimeRange=function(MinTime){this.MinTime=MinTime;this.SendMessageToListeners(CMScene.MESSAGE_TIME_RANGE_CHANGED);}
CMScene.prototype.GetTimeRange=function(){return(this.MinTime);}
CMScene.prototype.In=function(TheView,RefX,RefY,TheEvent){var Result=null;for(var i=this.Layers.length-1;(i>=0)&&(Result==null);i--){var FeatureIndex=this.Layers[i].In(TheView,RefX,RefY,TheEvent);if(FeatureIndex!=-1){Result={LayerIndex:i,FeatureIndex:FeatureIndex}}}return(Result);};CMScene.prototype.MouseDown=function(TheView,RefX,RefY,TheEvent){var Used=false;for(var i=this.Layers.length-1;(i>=0)&&(Used==false);i--){Used=this.Layers[i].MouseDown(TheView,RefX,RefY,TheEvent);}return(Used);};CMScene.prototype.MouseMove=function(TheView,RefX,RefY,TheEvent){var Used=false;for(var i=this.Layers.length-1;(i>=0)&&(Used==false);i--){Used=this.Layers[i].MouseMove(TheView,RefX,RefY,TheEvent);}return(Used);};CMScene.prototype.MouseUp=function(TheView,RefX,RefY,TheEvent){var Used=false;for(var i=this.Layers.length-1;(i>=0)&&(Used==false);i--){Used=this.Layers[i].MouseUp(TheView,RefX,RefY,TheEvent);}return(Used);};CMScene.prototype.Resize=function(TheView){for(var i=0;i<this.Layers.length;i++){this.Layers[i].Resize(TheView);}for(var i=0;i<this.MapElements.length;i++){var TheMapElement=this.MapElements[i];var TheSticky=TheMapElement.GetRightSticky();if(TheSticky!=null){var TheCanvasElement=this.GetCanvasMap().GetElement(CMMainContainer.CANVAS);var ParentWidth=jQuery(TheCanvasElement).width();if(TheSticky.MoveFlag){var Width=TheSettings.Xs[1]-TheSettings.Xs[0];TheSettings.Xs[0]=ParentWidth-TheSticky.Offset-Width;TheSettings.Xs[1]=TheSettings.Ys[0]+Width;}else{TheSettings.Xs[1]=ParentWidth-TheSticky.Offset;}}var TheSticky=TheMapElement.GetBottomSticky();if(TheSticky!=null){var TheCanvasElement=this.GetCanvasMap().GetElement(CMMainContainer.CANVAS);var ParentHeight=jQuery(TheCanvasElement).height();var TheSettings=TheMapElement.GetSetting("Rectangle","Coordinates");if(TheSticky.MoveFlag){var Height=TheSettings.Ys[1]-TheSettings.Ys[0];TheSettings.Ys[0]=ParentHeight-TheSticky.Offset-Height;TheSettings.Ys[1]=TheSettings.Ys[0]+Height;}else{TheSettings.Ys[1]=ParentHeight-TheSticky.Offset;}}}for(var i=0;i<this.Views.length;i++){this.Views[i].Resize();}this.Repaint();}
CMScene.prototype.Paint=function(TheView){if(this.NumRepaintBlocks==0){this.GetCanvasMap().AddToDebugPanel("CMScene.Paint Starting:"+CMUtilities.GetSeconds());this.NeedRepaint=false;this.IncrementRepaintBlocks();TheView.PaintStart();var Style=this.GetStyle(TheView,0,"Fill");if(Style!=undefined){TheView.SetStyle(Style);TheView.PaintBackground();TheView.RestoreStyle();}if(this.SelectedBackgroundIndex!=-1){this.Backgrounds[this.SelectedBackgroundIndex].Paint(TheView);}for(var i=0;i<this.Layers.length;i++){if(typeof this.Layers[i]=="undefined"){var j=12;}this.Layers[i].Paint(TheView);}for(var i=0;i<this.Layers.length;i++){this.Layers[i].PaintSelected(TheView);}for(var i=0;i<this.MapElements.length;i++){this.MapElements[i].Paint(TheView);}TheView.PaintEnd();this.DecrementRepaintBlocks();this.GetCanvasMap().AddToDebugPanel("CMScene.Paint Done: "+CMUtilities.GetSeconds());if(this.NeedRepaint)this.Repaint();}else{this.GetCanvasMap().AddToDebugPanel("CMScene.Paint NeedRepaint=true: "+CMUtilities.GetSeconds());this.NeedRepaint=true;}}
CMScene.prototype.Repaint=function(){for(var i=0;i<this.Views.length;i++){this.Paint(this.Views[i]);}this.GetCanvasMap().AddToDebugPanel("CMScene.Repaint Exit:"+CMUtilities.GetSeconds());}
CMScene.prototype.IncrementRepaintBlocks=function(){this.NumRepaintBlocks++;}
CMScene.prototype.DecrementRepaintBlocks=function(){this.NumRepaintBlocks--;}
CMScene.prototype.LayerListChanged=function(){this.SendMessageToListeners(CMScene.MESSAGE_LAYER_LIST_CHANGED,this);}
CMScene.prototype.LayerContentChanged=function(ItemThatChanged){this.SendMessageToListeners(CMScene.MESSAGE_LAYER_CONTENT_CHANGED,ItemThatChanged);}
CMScene.prototype.LayerSettingsChanged=function(ItemThatChanged){this.SendMessageToListeners(CMScene.MESSAGE_LAYER_SETTINGS_CHANGED,ItemThatChanged);this.Repaint();}
CMScene.prototype.SelectionChanged=function(ItemThatChanged){this.SendMessageToListeners(CMScene.MESSAGE_SELECTION_CHANGED,ItemThatChanged);this.Repaint();}
CMScene.prototype.SetProjector=function(TheProjector){this.TheProjector=TheProjector;};CMScene.prototype.GetProjector=function(){return(this.TheProjector);};CMScene.prototype.SetBoundsDirty=function(){this.TheBounds=null;}
CMScene.prototype.GetBounds=function(){if((this.Layers!=null)&&(this.TheBounds==null)){for(var i=0;i<this.Layers.length;i++){var TheLayer=this.Layers[i];if((this.TheBounds==null)&&(TheLayer.TheBounds!=null)){this.TheBounds=CMUtilities.CloneBounds(TheLayer.TheBounds);}else if(TheLayer.TheBounds!=null){CMUtilities.AddToBounds(this.TheBounds,TheLayer.TheBounds);}}}return(this.TheBounds);}
CMScene.prototype.InsertTime=function(Time){Time=parseFloat(Time);CMUtilities.InsertIntoSortedArray(this.Times,Time);this.SendMessageToListeners(CMScene.MESSAGE_TIME_SLICES_CHANGED);}
CMScene.prototype.DeleteTime=function(Time){Time=parseFloat(Time);var Index=this.Times.indexOf(Time);if(Index!=-1){this.Times.splice(Index,1);}this.SendMessageToListeners(CMScene.MESSAGE_TIME_SLICES_CHANGED);}
CMScene.prototype.CMItem_UnselectAll=CMItem.prototype.UnselectAll;CMScene.prototype.UnselectAll=function(SendMessageFlag){this.CMItem_UnselectAll(SendMessageFlag);for(var i=0;i<this.Layers.length;i++){this.Layers[i].UnselectAll(SendMessageFlag);}}