CMView2D.SettingDefintions={View2D:{MinZoom:{Name:"Min Zoom",Type:CMBase.DATA_TYPE_FLOAT,Default:-100000},MaxZoom:{Name:"Max Zoom",Type:CMBase.DATA_TYPE_FLOAT,Default:100000},MaxBounds:{Name:"Max Bounds",Type:CMBase.DATA_TYPE_COORDINATES,Default:100000}}};function CMView2D(){CMView.call(this);this.RefX=0;this.RefY=0;this.TimeSlices[0].Settings.View2D={MinZoom:-100000,MaxZoom:100000,MaxBounds:null};this.ZoomLevel=0;this.MinScale=1.0;this.TheCanvasElement=null;this.ToolHandler=null;this.TheContext=null;}CMView2D.prototype=Object.create(CMView.prototype);CMView2D.prototype.contructor=CMView2D;CMView2D.prototype.CMView_GetSettingsDefinitions=CMView.prototype.GetSettingsDefinitions;CMView2D.prototype.GetSettingsDefinitions=function(){var Result=this.CMView_GetSettingsDefinitions();for(Key in CMView2D.SettingDefintions){Result[Key]=CMView2D.SettingDefintions[Key];}return(Result);}
CMView2D.prototype.CheckMaxBounds=function(){var TheScale=this.GetScale();var RefWidth=this.TheCanvasElement.width*TheScale;var RefHeight=-this.TheCanvasElement.height*TheScale;var MaxBounds=this.GetSetting("View2D","MaxBounds");if(MaxBounds!=null){if((MaxBounds.Xs[1]-MaxBounds.Xs[0])<RefWidth){var NewCenterRefX=((MaxBounds.Xs[1]+MaxBounds.Xs[0])/2);this.RefX=NewCenterRefX-(RefWidth/2);}else{if(this.RefX<MaxBounds.Xs[0])this.RefX=MaxBounds.Xs[0];if((this.RefX+RefWidth)>MaxBounds.Xs[1])this.RefX=MaxBounds.Xs[1]-RefWidth;}if((MaxBounds.Ys[1]-MaxBounds.Ys[0])<-RefHeight){var NewCenterRefY=((MaxBounds.Ys[1]+MaxBounds.Ys[0])/2);this.RefY=NewCenterRefY-(RefHeight/2);}else{if(this.RefY>MaxBounds.Ys[1])this.RefY=MaxBounds.Ys[1];if((this.RefY+RefHeight)<MaxBounds.Ys[0])this.RefY=MaxBounds.Ys[0]-RefHeight;}}}
CMView2D.prototype.GetScale=function(){var CurrentScale=this.MinScale/Math.pow(2,this.ZoomLevel);return(CurrentScale);}
CMView2D.prototype.AddMobileEvents=function(){var mc=new Hammer(CanvasContainer);mc.get('pan').set({direction:Hammer.DIRECTION_ALL});var pinch=new Hammer.Pinch();mc.add([pinch]);mc.TheView=this;mc.on("pinch panleft panright panup pandown",function(ev){var TheView=mc.TheView;var RefDistance=TheView.GetRefWidthFromPixelWidth(CMMainContainer.GESTURE_PAN);var RefCenter=TheView.GetRefCenter();var RefX=RefCenter.RefX;var RefY=RefCenter.RefY;MapHeader.innerHTML=ev.type;if(ev.type=="panup"){RefY-=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="pandown"){RefY+=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="panleft"){RefX+=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="panright"){RefX-=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="pinch"){var ZoomLevel=TheView.GetZoomLevel();MapHeader.textContent=ev.additionalEvent;if(ev.additionalEvent=="pinchin"){TheView.ZoomTo(ZoomLevel-CMMainContainer.GESTURE_ZOOM);}else{TheView.ZoomTo(ZoomLevel+CMMainContainer.GESTURE_ZOOM);}}});}
CMView2D.prototype.MouseDown=function(TheEvent){var Used=false;if(!TheEvent){TheEvent=window.event;}CMMainContainer.HidePopupWindow();var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,this.TheCanvasElement);var PixelX=Coordinate.x;var PixelY=Coordinate.y;{var RefX=this.GetRefXFromPixelX(PixelX);var RefY=this.GetRefYFromPixelY(PixelY);if(this.ToolHandler!=null){Used=this.ToolHandler.MouseDown(this,RefX,RefY,TheEvent);}if(Used==false){if(this.CurrentTool==CMView.TOOL_HAND){this.DragX=this.GetRefXFromPixelX(PixelX);this.DragY=this.GetRefYFromPixelY(PixelY);this.Dragging=true;Used=true;}}if(Used==false){Used=this.GetParent(CMScene).MouseDown(this,RefX,RefY,TheEvent);}if(Used==false){this.DragX=this.GetRefXFromPixelX(PixelX);this.DragY=this.GetRefYFromPixelY(PixelY);this.Dragging=true;Used=true;}}return(Used);}
CMView2D.prototype.MouseMove=function(TheEvent){var Used=false;if(!TheEvent){TheEvent=window.event;}var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,this.TheCanvasElement);var PixelX=Coordinate.x;var PixelY=Coordinate.y;this.SendMessageToListeners(CMView.MESSAGE_MOUSE_MOVED,TheEvent);if(this.Dragging==true){var RefWidth=this.GetRefWidthFromPixelWidth(PixelX);var RefHeight=this.GetRefHeightFromPixelHeight(PixelY);this.RefX=this.DragX-RefWidth;this.RefY=this.DragY-RefHeight;this.CheckMaxBounds();this.Paint();}else{var RefX=this.GetRefXFromPixelX(PixelX);var RefY=this.GetRefYFromPixelY(PixelY);if(this.ToolHandler!=null){Used=this.ToolHandler.MouseMove(this,RefX,RefY,TheEvent);}if(Used==false){Used=this.GetParent(CMScene).MouseMove(this,RefX,RefY,TheEvent);}}return(Used);}
CMView2D.prototype.MouseUp=function(TheEvent){var Used=false;if(!TheEvent){TheEvent=window.event;}var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,this.TheCanvasElement);var PixelX=Coordinate.x;var PixelY=Coordinate.y;if(this.Dragging){this.DragX=0;this.DragY=0;this.Dragging=false;}else{var RefX=this.GetRefXFromPixelX(PixelX);var RefY=this.GetRefYFromPixelY(PixelY);if(this.ToolHandler!=null){Used=this.ToolHandler.MouseUp(this,RefX,RefY,TheEvent);}if(Used==false){Used=this.GetParent(CMScene).MouseUp(this,RefX,RefY,TheEvent);}}return(Used);}
CMView2D.prototype.MouseWheel=function(TheEvent){var Used=false;CMMainContainer.HidePopupWindow();if(!TheEvent){TheEvent=window.event;}var Delta=TheEvent.detail?TheEvent.detail*(-120):TheEvent.wheelDelta
if(Delta!=0){var NewZoomLevel=this.ZoomLevel;if(Delta>0){NewZoomLevel=NewZoomLevel+1;}else{NewZoomLevel=NewZoomLevel-1;}var MinZoom=this.GetSetting("View2D","MinZoom");var MaxZoom=this.GetSetting("View2D","MaxZoom");if(NewZoomLevel<MinZoom)NewZoomLevel=MinZoom;if(NewZoomLevel>MaxZoom)NewZoomLevel=MaxZoom;if(NewZoomLevel!=this.ZoomLevel){var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,this.TheCanvasElement);var MousePixelX=Coordinate.x;var MousePixelY=Coordinate.y;var MouseRefX=this.GetRefXFromPixelX(MousePixelX);var MouseRefY=this.GetRefYFromPixelY(MousePixelY);this.ZoomLevel=NewZoomLevel;var NewMouseRefWidth=this.GetRefWidthFromPixelWidth(MousePixelX);var NewMouseRefHeight=this.GetRefHeightFromPixelHeight(MousePixelY);this.RefX=MouseRefX-NewMouseRefWidth;this.RefY=MouseRefY-NewMouseRefHeight;CMDataset.ResetRequests();this.Paint();}}if(TheEvent.preventDefault)TheEvent.preventDefault()
return(Used);}
CMView2D.prototype.GetCoordinateStringFromEvent=function(TheEvent,CoordinateUnits){var TheCanvasElement=this.GetCanvasElement();var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,TheCanvasElement);var PixelX=Coordinate.x;var PixelY=Coordinate.y;var RefX=this.GetRefXFromPixelX(PixelX);var RefY=this.GetRefYFromPixelY(PixelY);var TheProjector=this.GetParent(CMMainContainer).GetProjector();var Text=CMUtilities.GetCoordinateString(RefX,RefY,CoordinateUnits,TheProjector,this);return(Text);}
CMView2D.prototype.GetExtent=function(){var TheExtent={};var TheScale=this.GetScale();TheExtent.XMin=this.RefX;TheExtent.YMax=this.RefY;TheExtent.XMax=this.RefX+(this.TheCanvasElement.width*TheScale);TheExtent.YMin=this.RefY-(this.TheCanvasElement.height*TheScale);return(TheExtent);}
CMView2D.prototype.SetRefCenter=function(RefX,RefY){var TheScale=this.GetScale();var RefWidth=this.TheCanvasElement.width*TheScale;var RefHeight=-this.TheCanvasElement.height*TheScale;this.RefX=RefX-(RefWidth/2);this.RefY=RefY-(RefHeight/2);if(this.MaxBounds!=null){if(this.RefX<this.MaxBounds.XMin)this.RefX=this.MaxBounds.XMin;if(this.RefY>this.MaxBounds.YMax)this.RefY=this.MaxBounds.YMax;if((this.RefX+RefWidth)>this.MaxBounds.XMax)this.RefX=this.MaxBounds.XMax-RefWidth;if((this.RefY+RefHeight)<this.MaxBounds.YMin)this.RefY=this.MaxBounds.YMin-RefHeight;}this.Paint();}
CMView2D.prototype.GetRefCenter=function(){var TheScale=this.GetScale();var RefWidth=this.TheCanvasElement.width*TheScale;var RefHeight=this.TheCanvasElement.height*TheScale;var Result={RefX:this.RefX+(RefWidth/2),RefY:this.RefY-(RefHeight/2)};return(Result);}
CMView2D.prototype.ZoomToBounds=function(NewBounds){if(NewBounds==null)alert("Sorry, you cannot call CMView2D.ZoomToBounds(NewBounds) with NewBounds=null.");else{var width=this.TheCanvasElement.width;var height=this.TheCanvasElement.height;var TheScale=Math.abs(NewBounds.XMax-NewBounds.XMin)/width;var yScale=Math.abs(NewBounds.YMax-NewBounds.YMin)/height;if(TheScale<yScale)TheScale=yScale;var OldZoomLevel=this.ZoomLevel;var MinZoom=this.GetSetting("View2D","MinZoom");var MaxZoom=this.GetSetting("View2D","MaxZoom");this.ZoomLevel=20;if(this.ZoomLevel>MaxZoom)this.ZoomLevel=MaxZoom;while((this.GetScale()<TheScale)&&(this.ZoomLevel>MinZoom)){this.ZoomLevel--;}if(this.ZoomLevel!=OldZoomLevel){CMDataset.ResetRequests();}var CenterRefX=(NewBounds.XMax+NewBounds.XMin)/2;var CenterRefY=(NewBounds.YMin+NewBounds.YMax)/2;this.SetRefCenter(CenterRefX,CenterRefY);}}
CMView2D.prototype.ZoomToMaxBounds=function(){var TheBounds=this.MaxBounds;if(TheBounds==null){TheBounds=this.GetParent(CMScene).GetBounds();}if(TheBounds!=null)this.ZoomToBounds(TheBounds);}
CMView2D.prototype.ZoomIn=function(){this.ZoomTo(this.ZoomLevel+1);}
CMView2D.prototype.ZoomOut=function(){this.ZoomTo(this.ZoomLevel-1);}
CMView2D.prototype.ZoomTo=function(ZoomLevel){var MinZoom=this.GetSetting("View2D","MinZoom");var MaxZoom=this.GetSetting("View2D","MaxZoom");if(ZoomLevel<MinZoom)ZoomLevel=MinZoom;if(ZoomLevel>MaxZoom)ZoomLevel=MaxZoom;if(ZoomLevel!=this.ZoomLevel){var RefX=this.GetRefXFromPixelX(this.TheCanvasElement.width/2);var RefY=this.GetRefYFromPixelY(this.TheCanvasElement.height/2);this.ZoomLevel=ZoomLevel;CMDataset.ResetRequests();this.SetRefCenter(RefX,RefY);}}
CMView2D.prototype.GetZoomLevel=function(){return(this.ZoomLevel);}
CMView2D.prototype.GetPixelXFromRefX=function(RefX){var PixelX;var TheScale=this.GetScale();PixelX=(RefX-this.RefX)/TheScale;return(PixelX);}
CMView2D.prototype.GetPixelYFromRefY=function(RefY){var TheScale=this.GetScale();var PixelY=(this.RefY-RefY)/TheScale;return(PixelY);};CMView2D.prototype.GetPixelFromRef=function(RefX,RefY){var PixelX=this.GetPixelXFromRefX(RefX);var PixelY=this.GetPixelYFromRefY(RefY);var Result={PixelX:PixelX,PixelY:PixelY}
return(Result);}
CMView2D.prototype.GetPixelWidthFromRefWidth=function(RefWidth){var TheScale=this.GetScale();var PixelWidth=RefWidth/TheScale;return(PixelWidth);}
CMView2D.prototype.GetPixelHeightFromRefHeight=function(RefHeight){var TheScale=this.GetScale();var PixelHeight=-RefHeight/TheScale;return(PixelHeight);}
CMView2D.prototype.GetRefWidthFromPixelWidth=function(PixelWidth){var TheScale=this.GetScale();var RefWidth=PixelWidth*TheScale;return(RefWidth);}
CMView2D.prototype.GetRefHeightFromPixelHeight=function(PixelHeight){var TheScale=this.GetScale();var RefHeight=-PixelHeight*TheScale;return(RefHeight);}
CMView2D.prototype.GetRefXFromPixelX=function(PixelX){var TheScale=this.GetScale();var RefX=PixelX*TheScale+this.RefX;return(RefX);};CMView2D.prototype.GetRefYFromPixelY=function(PixelY){var TheScale=this.GetScale();var RefY=-(PixelY*TheScale-this.RefY);return(RefY);};CMView2D.prototype.PaintRefBounds=function(TheBounds){this.PaintRefRect(TheBounds.XMin,TheBounds.XMax,TheBounds.YMin,TheBounds.YMax);}
CMView2D.prototype.PaintRefRect=function(XMin,XMax,YMin,YMax){var Result=this.GetPixelFromRef(XMin,YMax);var PixelXMin=Result.PixelX;var PixelYMin=Result.PixelY;var Result=this.GetPixelFromRef(XMax,YMin);var PixelXMax=Result.PixelX;var PixelYMax=Result.PixelY;this.PaintRect(PixelXMin,PixelXMax,PixelYMin,PixelYMax);};CMView2D.prototype.PaintRefArc=function(XMin,XMax,YMin,YMax,StartAngle,EndAngle){var Result=this.GetPixelFromRef(XMin,YMax);var PixelXMin=Result.PixelX;var PixelYMin=Result.PixelY;var Result=this.GetPixelFromRef(XMax,YMin);var PixelXMax=Result.PixelX;var PixelYMax=Result.PixelY;this.PaintArc(PixelXMin,PixelXMax,PixelYMin,PixelYMax,StartAngle,EndAngle);};CMView2D.prototype.PaintRefRoundedRect=function(XMin,XMax,YMin,YMax,RefXRadius,RefYRadius){var Result=this.GetPixelFromRef(XMin,YMax);var PixelXMin=Result.PixelX;var PixelYMin=Result.PixelY;var Result=this.GetPixelFromRef(XMax,YMin);var PixelXMax=Result.PixelX;var PixelYMax=Result.PixelY;var PixelXRadius=this.GetPixelWidthFromRefWidth(RefXRadius);var PixelYRadius=this.GetPixelWidthFromRefWidth(RefYRadius);this.PaintRoundedRect(PixelXMin,PixelXMax,PixelYMin,PixelYMax,PixelXRadius,PixelYRadius);}
CMView2D.prototype.PaintRefCircle=function(X,Y,RadiusInPixels){var Result=this.GetPixelFromRef(X,Y);var XInPixels=Result.PixelX;var YInPixels=Result.PixelY;this.PaintCircle(XInPixels,YInPixels,RadiusInPixels);};CMView2D.prototype.PaintRefText=function(Text,RefX,RefY,FontSize,HAlign,RadAngle){var TextWidth=this.GetTextWidthInPixels(Text);var RefTextWidth=this.GetRefWidthFromPixelWidth(TextWidth);if(RadAngle===undefined)RadAngle=0;var PixelX=this.GetPixelXFromRefX(RefX);var PixelY=this.GetPixelYFromRefY(RefY);var Bounds;if(RadAngle===0){if(HAlign==="center"){PixelX=this.GetPixelXFromRefX(RefX-(RefTextWidth/2));}else if(HAlign==="right"){PixelX=this.GetPixelXFromRefX(RefX-RefTextWidth);}else{}Bounds={XMin:PixelX,XMax:PixelX+TextWidth,YMin:PixelY-FontSize,YMax:PixelY};}else if(RadAngle===Math.PI/2){PixelX=this.GetPixelXFromRefX(RefX);if(HAlign==="center"){PixelY=this.GetPixelYFromRefY(RefY+(RefTextWidth/2));}else if(HAlign==="right"){PixelY=this.GetPixelYFromRefY(RefY+RefTextWidth);}else{PixelY=this.GetPixelYFromRefY(RefY);}Bounds={XMin:PixelX,XMax:PixelX+FontSize,YMin:PixelY,YMax:PixelY+TextWidth};}else if(RadAngle===-Math.PI/2){PixelX=this.GetPixelXFromRefX(RefX);if(HAlign==="center"){PixelY=this.GetPixelYFromRefY(RefY-(RefTextWidth/2));}else if(HAlign==="right"){PixelY=this.GetPixelYFromRefY(RefY-RefTextWidth);}else{PixelY=this.GetPixelYFromRefY(RefY);}Bounds={XMin:PixelX-FontSize,XMax:PixelX,YMin:PixelY-TextWidth,YMax:PixelY};}else{alert("Sorry, rotations other than 0,PI/2 and -PI/2 are not supported at this time");}if(this.CheckCollision(Bounds)==false){this.AddToCollisions(Bounds);this.PaintText(PixelX,PixelY,Text,RadAngle);}}
CMView2D.prototype.PaintRefLine=function(X1,Y1,X2,Y2){var Result=this.GetPixelFromRef(X1,Y1);var XInPixels1=Result.PixelX;var YInPixels1=Result.PixelY;var Result=this.GetPixelFromRef(X2,Y2);var XInPixels2=Result.PixelX;var YInPixels2=Result.PixelY;this.TheContext.beginPath();this.TheContext.moveTo(XInPixels1,YInPixels1);this.TheContext.lineTo(XInPixels2,YInPixels2);this.TheContext.stroke();}
CMView2D.prototype.PaintRefPoly2=function(Xs,Ys,Closed,Stroke){if(Xs!=undefined){var PixelX;var PixelY;var FirstPixelX;var FirstPixelY;var LastPixelX;var LastPixelY;for(var j=0;j<Xs.length;j++){var RefX=Xs[j];var RefY=Ys[j];Result=this.GetPixelFromRef(RefX,RefY);var PixelX=(Result.PixelX);var PixelY=(Result.PixelY);if(j==0){this.TheContext.beginPath();this.TheContext.moveTo(PixelX,PixelY);FirstPixelX=PixelX;FirstPixelY=PixelY;LastPixelX=PixelX;LastPixelY=PixelY;}if((PixelX!=LastPixelX)||(PixelY!=LastPixelY)){this.TheContext.lineTo(PixelX,PixelY);LastPixelX=PixelX;LastPixelY=PixelY;}}if(Closed){this.TheContext.lineTo(FirstPixelX,FirstPixelY);this.TheContext.fill();}if(Stroke===true){if((Closed==false)||(this.TheContext.shadowColor==undefined)){this.TheContext.stroke();}else{var TheShadowColor=this.TheContext.shadowColor;this.TheContext.shadowColor="rgba(0,0,0,0)";this.TheContext.stroke();this.TheContext.shadowColor=TheShadowColor;}}}}
CMView2D.prototype.PaintRefImage=function(TheImage,RefX,RefY){var Result=this.GetPixelFromRef(RefX,RefY);var XInPixels1=Result.PixelX;var YInPixels1=Result.PixelY;this.TheContext.drawImage(TheImage,XInPixels1,YInPixels1);}
CMView2D.prototype.PaintRefImageScaled=function(TheImage,RefX,RefY,RefWidth,RefHeight){var Type=typeof(RefX);if(Type=="object"){TheBounds=RefX;RefX=TheBounds.XMin;RefY=TheBounds.YMax;RefWidth=TheBounds.XMax-TheBounds.XMin;RefHeight=TheBounds.YMin-TheBounds.YMax;}var Result=this.GetPixelFromRef(RefX,RefY);var XInPixels1=Math.round(Result.PixelX);var YInPixels1=Math.round(Result.PixelY);var PixelWidth=this.GetPixelWidthFromRefWidth(RefWidth);var PixelHeight=this.GetPixelHeightFromRefHeight(RefHeight);PixelWidth=Math.round(PixelWidth);PixelHeight=Math.round(PixelHeight);this.TheContext.drawImage(TheImage,XInPixels1,YInPixels1,PixelWidth,PixelHeight);}
CMView2D.prototype.PaintRefPoly=function(TheCoordinates,Closed){if(TheCoordinates!=undefined){var RefX=TheCoordinates[0][0];var RefY=TheCoordinates[0][1];var Result=this.GetPixelFromRef(RefX,RefY);var PixelX=Math.round(Result.PixelX);var PixelY=Math.round(Result.PixelY);this.TheContext.beginPath();this.TheContext.moveTo(PixelX,PixelY);var LastPixelX=PixelX;var LastPixelY=PixelY;for(var j=1;j<TheCoordinates.length;j++){RefX=TheCoordinates[j][0];RefY=TheCoordinates[j][1];Result=this.GetPixelFromRef(RefX,RefY);PixelX=Math.round(Result.PixelX);PixelY=Math.round(Result.PixelY);if((PixelX!=LastPixelX)||(PixelY!=LastPixelY)){this.TheContext.lineTo(PixelX,PixelY);LastPixelX=PixelX;LastPixelY=PixelY;}}if(Closed)this.TheContext.fill();this.TheContext.stroke();}}
CMView2D.prototype.CreateInfoWindow=function(ID,RefX,RefY,WindowWidth,WindowHeight,TheHTML){var PixelX=this.GetPixelXFromRefX(RefX);var PixelY=this.GetPixelYFromRefY(RefY);var Offset=jQuery(this.TheCanvasElement).offset();var CanvasBounds=this.TheCanvasElement.getBoundingClientRect();PixelX+=CanvasBounds.left;PixelY+=CanvasBounds.top;var TheCanvasMap=this.GetParent(CMMainContainer);var TheImageFolder=TheCanvasMap.ImageFolder;var InfoWindow=CMUtilities.CreateInfoWindow(ID,PixelX,PixelY,WindowWidth,WindowHeight,TheHTML,TheImageFolder);return(InfoWindow);}