CMView.TOOL_HAND=1;CMView.TOOL_INFO=2;CMView.TOOL_EDIT=3;CMView.TOOL_ADD=4;CMView.TOOL_SELECT=5;CMView.MESSAGE_MOUSE_MOVED=CMBase.GetUniqueNumber();function CMView(){CMItem.call(this);this.CurrentTool=CMView.TOOL_SELECT;this.CollisionChecking=false;this.TheCanvasElement=null;this.ToolHandler=null;this.TheContext=null;this.CollisionArray=null;}CMView.prototype=Object.create(CMItem.prototype);CMView.prototype.contructor=CMView;CMView.prototype.GetContext=function(){return(this.TheContext);}
CMView.prototype.MouseDown=function(TheEvent){var Used=false;CMMainContainer.HidePopupWindow();return(Used);}
CMView.prototype.MouseMove=function(TheEvent){var Used=false;if(!TheEvent){TheEvent=window.event;}this.SendMessageToListeners(CMView.MESSAGE_MOUSE_MOVED,TheEvent);return(Used);}
CMView.prototype.MouseUp=function(TheEvent){var Used=false;if(!TheEvent){TheEvent=window.event;}var Coordinate=CMUtilities.GetElementCoordinate(TheEvent.clientX,TheEvent.clientY,this.TheCanvasElement);var PixelX=Coordinate.x;var PixelY=Coordinate.y;return(Used);}
CMView.prototype.MouseWheel=function(TheEvent){var Used=false;CMMainContainer.HidePopupWindow();if(!TheEvent){TheEvent=window.event;}var Delta=TheEvent.detail?TheEvent.detail*(-120):TheEvent.wheelDelta
if(TheEvent.preventDefault)TheEvent.preventDefault()
return(Used);}
CMView.prototype.GetCoordinateStringFromEvent=function(TheEvent,CoordinateUnits){return(Text);}
CMView.prototype.Setup=function(TheCanvasContainer,TheCanvasElement){this.TheCanvasContainer=TheCanvasContainer;this.TheCanvasElement=TheCanvasElement;this.TheContext=this.TheCanvasElement.getContext('2d');this.TheCanvasElement.style.cursor="crosshair";this.SetTool(CMView.TOOL_SELECT);}
CMView.prototype.Resize=function(){var TheElement=this.TheCanvasElement;var TheParent=TheElement.parentNode;var ParentWidth=jQuery(TheParent).width();var ParentHeight=jQuery(TheParent).height();TheElement.width=ParentWidth;TheElement.height=ParentHeight;}
CMView.prototype.SetToolHandler=function(NewToolHandler){this.ToolHandler=NewToolHandler;}
CMView.prototype.GetToolHandler=function(){return(this.ToolHandler);}
CMView.prototype.GetCanvasElement=function(){return(this.TheCanvasElement);}
CMView.prototype.GetCanvasContainer=function(){return(this.TheCanvasContainer);}
CMView.prototype.AddMouseEventHandlers=function(){var TheCanvasElement=this.GetCanvasElement();TheCanvasElement.TheView=this;TheCanvasElement.addEventListener("mousedown",function(TheEvent){if(this.TheView!=null){this.TheView.MouseDown(TheEvent);TheEvent.stopPropagation();}});TheCanvasElement.addEventListener("mousemove",function(TheEvent){if(this.TheView!=null){this.TheView.MouseMove(TheEvent);}});TheCanvasElement.addEventListener("mouseup",function(TheEvent){if(this.TheView!=null){this.TheView.MouseUp(TheEvent);}});var mousewheelevt=(/Firefox/i.test(navigator.userAgent))?"DOMMouseScroll":"mousewheel"
if(TheCanvasElement.attachEvent){TheCanvasElement.attachEvent("on"+mousewheelevt,function(TheEvent){var Result;CMMainContainer.HidePopupWindow();var TheEvent=window.event||TheEvent
var Result=this.TheView.MouseWheel(TheEvent);return(Result);});}else if(TheCanvasElement.addEventListener){TheCanvasElement.addEventListener(mousewheelevt,function(TheEvent){var Result;CMMainContainer.HidePopupWindow();var TheEvent=window.event||TheEvent
var Result=this.TheView.MouseWheel(TheEvent);return(Result);},false);}}
CMView.prototype.AddMobileEvents=function(){var mc=new Hammer(CanvasContainer);mc.get('pan').set({direction:Hammer.DIRECTION_ALL});var pinch=new Hammer.Pinch();mc.add([pinch]);mc.TheView=this;mc.on("pinch panleft panright panup pandown",function(ev){var TheView=mc.TheView;var RefDistance=TheView.GetRefWidthFromPixelWidth(CMMainContainer.GESTURE_PAN);var RefCenter=TheView.GetRefCenter();var RefX=RefCenter.RefX;var RefY=RefCenter.RefY;MapHeader.innerHTML=ev.type;if(ev.type=="panup"){RefY-=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="pandown"){RefY+=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="panleft"){RefX+=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="panright"){RefX-=RefDistance;TheView.SetRefCenter(RefX,RefY);}else if(ev.type=="pinch"){var ZoomLevel=TheView.GetZoomLevel();MapHeader.textContent=ev.additionalEvent;if(ev.additionalEvent=="pinchin"){TheView.ZoomTo(ZoomLevel-CMMainContainer.GESTURE_ZOOM);}else{TheView.ZoomTo(ZoomLevel+CMMainContainer.GESTURE_ZOOM);}}});}
CMView.prototype.SetTool=function(NewTool){switch(NewTool){case CMView.TOOL_HAND:this.TheCanvasElement.style.cursor="move";break;case CMView.TOOL_INFO:case CMView.TOOL_SELECT:this.TheCanvasElement.style.cursor="crosshair";break;case CMView.TOOL_EDIT:this.TheCanvasElement.style.cursor="crosshair";break;}this.CurrentTool=NewTool;}
CMView.prototype.GetTool=function(){return(this.CurrentTool);}
CMView.prototype.SetStyle=function(NewStyle,SaveCurrentStyle){if(SaveCurrentStyle!==false)this.TheContext.save();if((NewStyle!=null)&&(NewStyle!=undefined)){this.TheContext.shadowBlur=0;for(var key in NewStyle){this.TheContext[key]=NewStyle[key];}}}
CMView.prototype.SaveStyle=function(){this.TheContext.save();}
CMView.prototype.RestoreStyle=function(){this.TheContext.restore();}
CMView.prototype.PaintStart=function(){if(this.CollisionChecking){this.CollisionArray=[];}}
CMView.prototype.Paint=function(){this.TheContext.clearRect(0,0,this.TheCanvasElement.width,this.TheCanvasElement.height);this.GetParent(CMScene).Paint(this);};CMView.prototype.PaintEnd=function(){this.ResetCollisions();}
CMView.prototype.CheckCollision=function(Bounds){var Result=false;if(this.CollisionArray!==null){for(var i=0;(i<this.CollisionArray.length)&&(Result==false);i++){if(CMUtilities.BoundsOverlap(Bounds,this.CollisionArray[i])){Result=true;}}}return(Result);}
CMView.prototype.AddToCollisions=function(Bounds){if(this.CollisionArray!==null){this.CollisionArray.push(Bounds);}}
CMView.prototype.ResetCollisions=function(){if(this.CollisionChecking){this.CollisionArray=[];}}
CMView.prototype.GetTextWidthInPixels=function(Text){var TextWidth=this.TheContext.measureText(Text).width;return(TextWidth);}
CMView.prototype.PaintImage=function(TheImage,PixelX,PixelY){this.TheContext.drawImage(TheImage,PixelX,PixelY);};CMView.prototype.PaintBackground=function(){{this.TheContext.fillRect(0,0,this.TheCanvasElement.width,this.TheCanvasElement.height);}};CMView.prototype.PaintCircle=function(X,Y,RadiusInPixels){this.TheContext.beginPath();this.TheContext.arc(X,Y,RadiusInPixels,0,2*Math.PI);if(this.TheContext.strokeStyle!=null)this.TheContext.stroke();if(this.TheContext.fillStyle!=null)this.TheContext.fill();};CMView.prototype.PaintRect=function(PixelXMin,PixelXMax,PixelYMin,PixelYMax){if(this.TheContext.fillStyle!=null){this.TheContext.fillRect(PixelXMin,PixelYMin,PixelXMax-PixelXMin,PixelYMax-PixelYMin);}if(this.TheContext.strokeStyle!=null){if((this.TheContext.fillStyle==null)||(this.TheContext.shadowColor==undefined)){this.TheContext.stroke();}else{var TheShadowColor=this.TheContext.shadowColor;this.TheContext.shadowColor="rgba(0,0,0,0)";this.TheContext.strokeRect(PixelXMin,PixelYMin,PixelXMax-PixelXMin,PixelYMax-PixelYMin);this.TheContext.shadowColor=TheShadowColor;}}}
CMView.prototype.PaintArc=function(PixelXMin,PixelXMax,PixelYMin,PixelYMax,StartAngle,EndAngle){var PixelCenterX=(PixelXMin+PixelXMax)/2;var PixelCenterY=(PixelYMin+PixelYMax)/2;var Radius=(PixelXMax-PixelXMin)/2;this.TheContext.save();this.TheContext.translate(PixelCenterX,PixelCenterY);var HeightFactor=(PixelYMax-PixelYMin)/(PixelXMax-PixelXMin);this.TheContext.scale(1,HeightFactor);this.TheContext.beginPath();this.TheContext.arc(0,0,Radius,StartAngle,EndAngle,false);this.TheContext.restore();if(this.TheContext.strokeStyle!=null){this.TheContext.stroke();}if(this.TheContext.fillStyle!=null){this.TheContext.fill();}}
CMView.prototype.PaintRoundedRect=function(PixelXMin,PixelXMax,PixelYMin,PixelYMax,PixelXRadius,PixelYRadius){if(typeof PixelYRadius==='undefined'){PixelYRadius=PixelXRadius;}this.TheContext.beginPath();this.TheContext.moveTo(PixelXMin+PixelXRadius,PixelYMin);this.TheContext.lineTo(PixelXMax-PixelXRadius,PixelYMin);this.TheContext.quadraticCurveTo(PixelXMax,PixelYMin,PixelXMax,PixelYMin+PixelYRadius);this.TheContext.lineTo(PixelXMax,PixelYMax-PixelYRadius);this.TheContext.quadraticCurveTo(PixelXMax,PixelYMax,PixelXMax-PixelXRadius,PixelYMax);this.TheContext.lineTo(PixelXMin+PixelXRadius,PixelYMax);this.TheContext.quadraticCurveTo(PixelXMin,PixelYMax,PixelXMin,PixelYMax-PixelYRadius);this.TheContext.lineTo(PixelXMin,PixelYMin+PixelYRadius);this.TheContext.quadraticCurveTo(PixelXMin,PixelYMin,PixelXMin+PixelXRadius,PixelYMin);this.TheContext.closePath();if(this.TheContext.strokeStyle!=null)this.TheContext.stroke();if(this.TheContext.fillStyle!=null)this.TheContext.fill();}
CMView.prototype.PaintText=function(XInPixels,YInPixels,Text,RadAngle){if(RadAngle!=undefined){this.TheContext.translate(XInPixels,YInPixels);this.TheContext.rotate(RadAngle);this.TheContext.fillText(Text,0,0);this.TheContext.rotate(-RadAngle);this.TheContext.translate(-XInPixels,-YInPixels);}else{this.TheContext.fillText(Text,XInPixels,YInPixels);}}